### ISSUE TITLE
Rewrite Roadmap

### ISSUE THREAD

**Issue by Wumpotamus** [Wumpotamus/BigBrother#1]
Here's the list of what all needs to be done before the rewrite is completed.
- [ ] Redo inventory (it needs completely redone)
- [ ] Packet handling will have to be cleaned up.
- [ ] Skins will have to be readded.
- [ ] Item frame entities will have to be readded.
- [ ] Block and item conversions need to be cleaned up.
